spring.datasource.url=jdbc:mariadb://localhost:3306/games
spring.datasource.username=games_user
spring.datasource.password={cipher}80edd390e21dc6cfc99f43cdde81ad36f7d186dfd4b2e560362f0a923ce6de76
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

logging.level.org.springframework=DEBUG
